### ISSUE TITLE
Firefox error & Extension for Jupyter Lab

### ISSUE THREAD

**Issue by ManuelBanza** [TiesdeKok/chat-gpt-jupyter-extension#1]
Thank you for this great tool!

Are you considering doing it for jupyter lab?

Also I got the extension to work in chrome but in firefox just gives me this error:

![imagem](https://user-images.githubusercontent.com/53525022/209661515-a943bd82-8c8c-41fc-a2f3-c93f5b6a4e88.png)

However it is set to true.

Cheers!

**Comment by TiesdeKok** [comment]
Hi @ManuelBanza,

Thanks for the bug report; I mixed up the manifests, which was an easy fix. Things should work properly now in Firefox with version V0.1.2

I am planning to add Jupyter Lab support; it is next on my list. So hopefully soon.

Ties

**Comment by ManuelBanza** [comment]
It works now. Thanks!

**Comment by TiesdeKok** [comment]
FYI @ManuelBanza , I just added Jupyter Lab support to the extension! The Jupyter Lab interface is substantially more complex than traditional notebooks, so please let me know if you run into any issues, and I'll look into fixing them. 🧰
