### ISSUE TITLE
Can you put functions on celltoolbar of the focused CODE cell?

### ISSUE THREAD

**Issue by MRYingLEE** [TiesdeKok/chat-gpt-jupyter-extension#10]
Now the functions are on the top toolbar.

It is not convenient for a user to move cursor from the bottom to the top to pick up a function.

Also, if possible, please add some key shortcuts to the functions. So a user doesn't need to switch from keyboard to mouse from time to time.

Thank you in advance,

**Comment by TiesdeKok** [comment]
Shortcut support is high on my priority list, so that'll be implemented soon. I am not planning to add the buttons to the focal cell at this point to keep things reasonably lean.

**Comment by TiesdeKok** [comment]
Hi @MRYingLEE  I just pushed a new full release (V0.6.0) to [Github](https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.6.0) and to the Chrome web store (which might take a few days to get approved).

This new version includes shortcut support! You can change/set the shortcuts through the native shortcut handler for Chrome extensions. You can get there by clicking on the extension icon (the orange rocket) and clicking shortcuts. 

I will close this issue for now, but if that doesn't meet your needs, please re-open it and describe what you are looking.
