### ISSUE TITLE
customize_prompt

### ISSUE THREAD

**Issue by ZS520L** [TiesdeKok/chat-gpt-jupyter-extension#12]
It is highly recommended to add the ability to customize prompt to meet the user's personalized needs

**Comment by TiesdeKok** [comment]
I am working on adding the functionality to ask it custom questions. Is that what you are looking for, or would you like to be able to adjust the existing prompts that are used when you click the default action buttons? The latter might be harder to achieve, but I can look into it.

**Comment by TiesdeKok** [comment]
Hi @ZS520L , I just pushed a new full release (V0.6.0) to [Github](https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.6.0) and to the Chrome web store (which might take a few days to get approved). 

This new version includes the ability to ask a custom question by typing or through your microphone. 

I will close this issue for now, but if that doesn't meet your needs, feel free to re-open it and describe what you are looking for in more detail.
