### ISSUE TITLE
I cannot select the model cause the fill form is black I cannot see or choose any

### ISSUE THREAD

**Issue by mksamanes** [TiesdeKok/chat-gpt-jupyter-extension#13]
I cannot select the model cause the fill form is black I cannot see or choose any, so I cannot use the tool.
Why I cannot choose any model?

**Comment by TiesdeKok** [comment]
I supect I know why this might be happening. Could you still try to use the extension like normal, even without selecting anything? It is possible that you need to use the extension once for the form field to populate once you authenticate with OpenAI. There is a default model selected; it just doesn't currently show in the dropdown (which I will add to my list of fixes to implement).

**Comment by TiesdeKok** [comment]
Hi  @mksamanes I just pushed a pre-release of version V0.5.9 that includes a fix for this issue. It is not yet available on the Chrome store as it needs a bit more testing, but you can try it here: https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.5.9

**Comment by TiesdeKok** [comment]
Hi @mksamanes , I just pushed a new full release (V0.6.0) to [Github](https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.6.0) and to the Chrome web store (which might take a few days to get approved). That includes a fix for your problem, so everything should work as expected now.

I will close this issue for now, but if you still run into any problems, feel free to re-open it! 😄
