### ISSUE TITLE
Edge cases not initializing correctly

### ISSUE THREAD

**Issue by AJI83** [TiesdeKok/chat-gpt-jupyter-extension#14]
Hi, "After installing the extension and refreshing the notebook page you should see the buttons automatically show up, you don't have to install them separately. There are a few edge cases where things might not initialize correctly, which could prevent the buttons from showing up on your end. I'd be happy to help you debug that if you open an issue on the Github page: https://github.com/TiesdeKok/chat-gpt-jupyter-extension/issues"
any help is welcome

**Comment by TiesdeKok** [comment]
Of course, what operating system are you on, and what version of Jupyter you are using (e.g., lab vs. notebook + the package version)? Also, if you can share a screenshot of what your notebook interface looks like, that'd be helpful too.

**Comment by AJI83** [comment]
> Of course, what operating system are you on, and what version of Jupyter you are using (e.g., lab vs. notebook + the package version)? Also, if you can share a screenshot of what your notebook interface looks like, that'd be helpful too.

Hi Sir, Windows 10, Jupyter Notebook 6.3.0. within anaconda distr.

**Comment by TiesdeKok** [comment]
> Hi Sir, Windows 10, Jupyter Notebook 6.3.0. within anaconda distr.

Is it not showing up for the classical Jupyter Notebook and Jupyter Lab, or does it only not work for one of them? Can you check the Chrome console for any errors that could hint at what is happening? You can see the Chrome devtools window by right-clicking anywhere on the page and selecting "inspect." The console is shown under the Console tab, although you might have to refresh the window with the console open to see all the messages.

**Comment by TiesdeKok** [comment]
Hi @AJI83  I just pushed a pre-release of version V0.5.9 that includes a potential fix for this issue. It is not yet available on the Chrome store as it needs a bit more testing, but you can try it here: https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.5.9

**Comment by AJI83** [comment]
> > Hi Sir, Windows 10, Jupyter Notebook 6.3.0. within anaconda distr.
> 
> Is it not showing up for the classical Jupyter Notebook and Jupyter Lab, or does it only not work for one of them? Can you check the Chrome console for any errors that could hint at what is happening? You can see the Chrome devtools window by right-clicking anywhere on the page and selecting "inspect." The console is shown under the Console tab, although you might have to refresh the window with the console open to see all the messages.

**Comment by AJI83** [comment]
it worked by switching to older version and fixing the issue of NB extensions in Jupyter.
I will try new version, thank you

**Comment by TiesdeKok** [comment]
I just pushed a new full release (V0.6.0) to [Github](https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.6.0) and to the Chrome web store (which might take a few days to get approved). I was able to pin-point what is causing the buttons not to show up and this version includes a fix. 

I will close this issue for now, but if you still run into any problems, feel free to re-open it! 😄
