### ISSUE TITLE
Can not select AI Provider?

### ISSUE THREAD

**Issue by ouchen2017** [TiesdeKok/chat-gpt-jupyter-extension#15]
Which AI Provider do you want to use? 
It is loading and does not display.

**Comment by TiesdeKok** [comment]
Hi @ouchen2017 , thanks for the bug report! I just pushed a pre-release of version V0.5.9 to the github repo that includes a fix for this issue. It is not yet available on the Chrome store as it needs a bit more testing, but you can try it here: https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.5.9

**Comment by TiesdeKok** [comment]
Hi @ouchen2017, I just pushed a new full release (V0.6.0) to [Github](https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.6.0) and to the Chrome web store (which might take a few days to get approved). That includes a fix for your problem, so everything should work as expected now.

I will close this issue for now, but if you still run into any problems, feel free to re-open it! 😄
