### ISSUE TITLE
AI provider is not available(ver0.6.0)

### ISSUE THREAD

**Issue by Doi-Ryota** [TiesdeKok/chat-gpt-jupyter-extension#16]
I have tried local install and installing from Chrome, but none of them worked.
This is a bug that used to be present, but seems to be persisting.

**Comment by TiesdeKok** [comment]
Thanks for the bug report, would you mind sharing some more information about what you mean by "AI provider is not available"?

**Comment by MRYingLEE** [comment]
Recently my ChatGPT account expired while my OpenAI's API key is still valid.  Then I met a similar issue on the options page, just like the below:

![image](https://user-images.githubusercontent.com/11193534/230706359-8f14e8a5-c042-48c0-9958-df109b094242.png)

Basically, the extension failed to access ChatGPT to get some information. 

Maybe you can make API access the default way and try to access ChatGPT only if an end user chooses it.

**Comment by Orionsic** [comment]
Same here

**Comment by TiesdeKok** [comment]
See my other reply for a temporary solution for some people. I will try to get this fix asap.

https://github.com/TiesdeKok/chat-gpt-jupyter-extension/issues/22#issuecomment-1518095400
