### ISSUE TITLE
There is no way I can hide and show the buttons when I need them and when I don't

### ISSUE THREAD

**Issue by AgZ-3mk** [TiesdeKok/chat-gpt-jupyter-extension#17]
Tbh, the extension works perfectly, but I tried hiding the buttons in toolbar of the extenstion, and I cant.
It would be great if you can have a shortcut for example to toggle the buttons (show/hide)
![image_2023-04-07_135615624](https://user-images.githubusercontent.com/44108506/230597323-fc31453b-7dc6-43ff-8f13-07f883fa51f9.png)

**Comment by TiesdeKok** [comment]
Gotcha, that functionality shouldn't be too hard to add. The primary challenge will be making it work UI-wise; I wouldn't want people to get confused if their buttons disappear. Maybe I can repurpose the little robot icon as the hide-show button and indicator. 

I'll add it to my to-do list!
