### ISSUE TITLE
extension doesn't work on chrome

### ISSUE THREAD

**Issue by hosseinxj0152** [TiesdeKok/chat-gpt-jupyter-extension#2]
Hello! thank you for creating such a useful extension but I have installed the extension in google chrome and opened a jupyter notebook and nothing related to the extension shows up. could you help me fix that?

**Comment by TiesdeKok** [comment]
Definitely! This could be due to a few different reasons, would you mind showing a screenshot of your jupyter notebook setup (eg an empty notebook)? Also, does the URL of the page end with `.ipynb` or something else?

**Comment by hosseinxj0152** [comment]
Here's the screenshot.
![image](https://user-images.githubusercontent.com/13707431/210024945-4bf629c6-beb0-4ae0-b7df-d92fdad5f585.png)

**Comment by TiesdeKok** [comment]
Hi @hosseinxj0152,

Thanks for your patience, I was working on adding Jupyter Lab support to the extension, which might have fixed the issue. 

Can you uninstall the extension and reinstall it with version V0.2.1.?
If that doesn't resolve the issue, can you check your Chrome DevTools console for any messages/warnings/errors that might explain why the extension is not initiating? You can access the console by right click on a cell --> inspect --> console at the top.

**Comment by abhishekmamdapure** [comment]
Hello @TiesdeKok, I have installed the latest version 0.2.3, however I am facing the issue where it says:

```
Failed to load response from ChatGPT:
Failed to fetch
```

Anything I might be doing wrong ?

**Comment by TiesdeKok** [comment]
> Hello @TiesdeKok, I have installed the latest version 0.2.3, however I am facing the issue where it says:
> 
> ```
> Failed to load response from ChatGPT:
> Failed to fetch
> ```
> 
> Anything I might be doing wrong ?

Hmm, does ChatGPT work normally (ie through the regular OpenAI website)? This sounds like an OpenAI issue, but it could be something else is going on with the extension. If it doesn't resolve itself, I can look into it tomorrow.

**Comment by TiesdeKok** [comment]
I will close this issue for now, but if the issues persist you are welcome to let me know!
