### ISSUE TITLE
The Chrome extension doesn't work even though I have entered the API key

### ISSUE THREAD

**Issue by DragonMeowww** [TiesdeKok/chat-gpt-jupyter-extension#22]
<img width="466" alt="Screenshot 2023-04-20 151505" src="https://user-images.githubusercontent.com/96011846/233303630-666a70ac-bf0d-4286-a5b2-2e0f2a04b1cd.png">

I tried to enter but nothing happen and the option about ai provider doesn't seem to work as well. Please help!

**Comment by AlexNetman** [comment]
It worked one time for me but then gives error
![image](https://user-images.githubusercontent.com/4558228/233630446-82195fde-52eb-479a-91a9-19b999268044.png)

**Comment by TiesdeKok** [comment]
Thanks for the bug reports! Seeing the console log was especially helpful, thanks @AlexNetman .

I was able to reproduce the issue on my end, and **the temporary solution is to open up the ChatGPT interface (chat.openai.com) and ask it a question. Refreshing the settings page after that should resolve it.**

I need to rework some of the code for the options page such that:

1. It detects authentication issues and pops open the ChatGPT page.
2. Allows the user to ignore the ChatGPT provider and still select the API option; currently, not being able to access the ChatGPT web interface prevents getting to the API option.

Unfortunately, I am super busy with work for the next nine days, but I will try to resolve this ASAP.

**Comment by SamuelLAN** [comment]
I have tried the temporary solution, but it still doesn't work.

![image](https://user-images.githubusercontent.com/8002981/234448070-de59bb11-9c64-43b4-9dbb-bc403281855b.png)
