### ISSUE TITLE
not popping out from the current tab to another tab

### ISSUE THREAD

**Issue by planetlibrary** [TiesdeKok/chat-gpt-jupyter-extension#24]
![image](https://user-images.githubusercontent.com/102426034/233677650-02e49e69-7bd4-407b-bbd0-a15cfbdeebb2.png)
Here I can not find any button that can make the output screen available in another tab. also I can not scroll through the output screen.

**Comment by TiesdeKok** [comment]
It is, unfortunately, not possible to open up the output screen in a different tab. Using JupyterLab provides a little greater control in that regard.

Regarding the scroll not working, that is something I can look into. Your screenshot suggests that you are using a custom CSS style for your notebook. Could it be that this is causing the scrolling issue?

**Comment by planetlibrary** [comment]
Yeah, using Jupyter Lab provides a much greater and enhanced control over the notebook. And thanks a lot for such wonderful extension. Hope this feature will be available in VS Code soon.
