### ISSUE TITLE
Plan and billing details

### ISSUE THREAD

**Issue by gf199x** [TiesdeKok/chat-gpt-jupyter-extension#25]
When I tried to use any function of this extension, I face a problem as below

Failed to load response from ChatGPT:
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

I am wondering it means we need to top up to our API account before using now?

**Comment by TiesdeKok** [comment]
Hmm, that is something I haven't seen on my end. You shouldn't need to, but maybe there is an edge case where things break.

I'll look into it next week when I am back from traveling.

**Comment by scipio1465** [comment]
I have the same problem. I use Firefox on a Linux machine

**Comment by prateekvishnu** [comment]
text-davinci-002-render-sha in ChatGPT Webapp works (after logging in another tab), Getting the same error with OpenAI API and gpt-3.5-turbo

**Comment by ShriVibhu-Giriraj** [comment]
Failed to load response from ChatGPT:
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
