### ISSUE TITLE
Stuck on after logging into ChatGPT

### ISSUE THREAD

**Issue by isai1029** [TiesdeKok/chat-gpt-jupyter-extension#26]
It was working fine but past couple hours this happened and it does not work.

<img width="976" alt="Screen Shot 2023-04-26 at 7 32 47 PM" src="https://user-images.githubusercontent.com/124097591/234744933-36548db7-f17a-4fde-a414-7b57e60e4a9b.png">

**Comment by TiesdeKok** [comment]
Sorry to hear that! I have some things that need work, but that won't be until I am back from traveling next week.

In the meantime, does chatgpt itself work?

Any issues on my end are always resolved by opening up chatgpt, running a test message, and then refreshing the notebook page. But this might be a different issue.

**Comment by isai1029** [comment]
Hello,
Despite doing still does not work and ChatGPT is working. I understand you are busy just thankful you have created this very useful tool!
