### ISSUE TITLE
Failed to load response from ChatGPT

### ISSUE THREAD

**Issue by marco577** [TiesdeKok/chat-gpt-jupyter-extension#29]
Hello, after installing and setting up the API key when I try to use it the following error appears:
Failed to load response from ChatGPT:
{"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by TiesdeKok** [comment]
Does your account have access to the `gpt-4` API? In order to use the `gpt-4` endpoint you need to have access, which you can request here: https://openai.com/waitlist/gpt-4-api

**Comment by marco577** [comment]
Got it, it worked, thanks.
