### ISSUE TITLE
can not see  Format tool menu?

### ISSUE THREAD

**Issue by 103style** [TiesdeKok/chat-gpt-jupyter-extension#35]
as a new jupyter user, please tell me how to show the tool menus.

i install jupyter from: https://docs.jupyter.org/en/latest/running.html

and then open the terminal,

run `jupyter notebook`,

then click  new notebook
<img width="1260" alt="image" src="https://github.com/TiesdeKok/chat-gpt-jupyter-extension/assets/14230909/bd4e6862-5ef6-480b-9eeb-2c7e85fb5abb">

and show me like 
<img width="1320" alt="image" src="https://github.com/TiesdeKok/chat-gpt-jupyter-extension/assets/14230909/80c90acd-54dd-4ce5-b3d2-52d80f045679">

**Comment by whuTuTu** [comment]
我也
