### ISSUE TITLE
Suggested enhancement

### ISSUE THREAD

**Issue by ifuchs** [TiesdeKok/chat-gpt-jupyter-extension#4]
It would be helpful if you could ask ChatGPT to use the focal cell as input and make whatever changes you specify and that would be a new cell.

**Comment by ifuchs** [comment]
It appears you can do exactly this by adding a comment.

**Comment by ifuchs** [comment]
Although it is not added to a cell which might make it easier to use the ChatGPT output.

**Comment by TiesdeKok** [comment]
Hi @ifuchs, that is right; you can achieve that functionality by adding comments (which is how I use it too). I could add a "custom instruction" button to streamline that, but I am not sure it would add much convenience over the existing comment + complete approach.

I have it on my todo list to make it easier to get the generated code back into a cell. Currently, I am thinking of adding a "copy code" button to the generation pane, which would automatically identify code blocks and provide a copy button for them. I might even be able to make the button "auto-inject" the code into the active cell. I'll have to play around with that. My primary concern is that I don't want to overwrite/delete any user code accidentally, so it would require some more thought to implement correctly & safely.

**Comment by TiesdeKok** [comment]
HI @ifuchs, FYI, the new version I just released ([0.2.3](https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.2.3)) adds a copy button to code blocks!

I will consider this issue resolved for the time being, but you are welcome to add any new or additional suggestions.

**Comment by ifuchs** [comment]
Thanks!
