### ISSUE TITLE
Extension not running chatgpt after signing in - Brave browser

### ISSUE THREAD

**Issue by JJ0BY** [TiesdeKok/chat-gpt-jupyter-extension#5]
This is occurring in brave. I have tried direct download and through google web extensions. 

It worked once when I reinstalled but it will not work afterwards. 

It shows the prompt below:

Please login and pass Cloudflare check at [chat.openai.com](https://chat.openai.com/)
Still not working? Please open an issue on the GitHub repository. Thanks!

The prompt continues despite me signing in.

**Comment by TiesdeKok** [comment]
Hi @JJ0BY, unfortunately, the brave browser is not currently supported. It only works in "standard" browsers such as Chrome, Edge, or Firefox. I don't currently have the bandwidth to add Brave browser support, but if someone else wants to tackle it, they are more than welcome to.
