### ISSUE TITLE
Can you add a feature to select the language of the conversation?

### ISSUE THREAD

**Issue by Hdaisen** [TiesdeKok/chat-gpt-jupyter-extension#6]
Reading in English is a bit difficult for me, and I would like the results returned by ChatGPT to be in my native language.

**Comment by TiesdeKok** [comment]
Hi @Hdaisen,

Apologies for missing your issue! Adding localization support is possible but would require quite a major overhaul. I will add it to the list of features, but it is low on my priority list. This might be a good first issue for someone to pick up; the [chatgpt-google-extension](https://github.com/wong2/chatgpt-google-extension) provides an example of how localization could be added. 

In the meantime, I've added the ability to ask a custom question in V0.6.0, and you can pretty easily get ChatGPT/GPT-4 to reply in a different language by starting your question with "Please answer in XXX" and then asking your question in your language of choice. Using that approach, I can ask a question in Dutch and have it reply in Dutch, for example. 😄
