### ISSUE TITLE
Will you support the newly published official ChatGPT api?

### ISSUE THREAD

**Issue by MRYingLEE** [TiesdeKok/chat-gpt-jupyter-extension#7]

**Comment by TiesdeKok** [comment]
I definitely could add official API support if there is a need for it. Can you help me understand under what circumstances the official API would be preferable over the current setup? What benefits does it provide that outweigh the costs? Thanks! 😄

**Comment by MRYingLEE** [comment]
1. Sometimes, although I have logined to ChatGPT, your extension couldn't detect my connection. I understand it is not because of your code.
2. The official API is much faster than the web version.
3. For privacy, I or my employer don't like to transfer code to a 3rd party beyond OpenAI.

**Comment by TiesdeKok** [comment]
Ah, that makes sense. Thanks for clarifying. I'll be OOT for a few days but I'll work on adding official API support once I am back.

**Comment by TiesdeKok** [comment]
Hi @MRYingLEE,

Thanks for your patience; this was more work than I had anticipated. 

But it is done! I just pushed V0.5.0 to the repo, which includes the option to use the official API and a model of your choosing. 

Let me know if you run into any issues!

**Comment by MRYingLEE** [comment]
It works very well with the official OpenAI API. Thank you.
