### ISSUE TITLE
Add ability to ask specific questions?

### ISSUE THREAD

**Issue by KoalaPS123** [TiesdeKok/chat-gpt-jupyter-extension#8]
Have you thought about adding the ability to ask specific questions, or for the user to be able to ask follow up questions regarding answers. I've found that's where the beauty of chatgpt lies, that I can converse with it to land with a good final result, 

https://github.com/jflam/chat-gpt-jupyter-extension

Has an example of something like this. But I've found the simple interface you offer makes your product better to use.

**Comment by TiesdeKok** [comment]
Thanks for the suggestions! I have been thinking about similar functionality, and I plan to add it soon. Once I find some time I will work on it together with implementing the official API functionality. So stay tuned!

**Comment by TiesdeKok** [comment]
Hi @KoalaPS123 , I just pushed a pre-release of version V0.5.9 that includes the option to ask a custom question, either by typing or by asking it verbally through your microphone. It is not yet available on the Chrome store as it needs a bit more testing, but you can try it here: https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.5.9

**Comment by TiesdeKok** [comment]
Hi @KoalaPS123  I just pushed a new full release (V0.6.0) to [Github](https://github.com/TiesdeKok/chat-gpt-jupyter-extension/releases/tag/0.6.0) and to the Chrome web store (which might take a few days to get approved).

This new version includes the ability to ask a custom question by typing or through your microphone.

I will close this issue for now, but if that doesn't meet your needs, feel free to re-open it and describe what you are looking for in more detail.
