### ISSUE TITLE
Can you support Colab and JupyterLite Retro?

### ISSUE THREAD

**Issue by MRYingLEE** [TiesdeKok/chat-gpt-jupyter-extension#9]
Colab is a popular Jupyter service for data scientists.

To my surprise, the extension supports JupyterLite Lab. At the same time, it does not support JupyterLite Retro. JupyterLite (https://jupyterlite.readthedocs.io/) could become more popular because it runs entirely in a browser.

If it only takes you a few hours to support these 2 services, you may try.

Sorry, I am not familiar with the front end, or I will find out the way to do so and contribute my code to you.

Thank you in advance,

**Comment by TiesdeKok** [comment]
Thanks for the suggestion; I had not considered JupyterLite instances. I'll look into it. The primary challenge will be to reliably identify them, as I currently rely on the following matching rules to fire up the extension:

```json
      "matches": [
        "*://*/*.ipynb",
        "*://*/lab*"
      ],
```

I want to avoid making these too general; the more specific, the better. 

Google Colab is also on my list, but with low priority at this point.
